docs_dir: doc
site_dir: latest
site_name: SPUL Connector
theme: readthedocs
pages:
    - Home: index.md
    - Introduction: introduction.md
    - Getting started: getting-started.md
    - Install: install.md
    - Test: test.md
    - Contribute: contribute.md
